name: Main Build

on:
  push:
    branches:
      - publish-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./Mindbox.LibraryTemplate.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore

      - name: Pack
        run: dotnet pack ./Mindbox.LibraryTemplate.sln -c Release -p:BuildNumber=${{ github.run_number }} -p:VersionTag="-dev"

      - name: Publish
        run: dotnet nuget push **/*.nupkg -k ${{secrets.MINDBOX_PRIVATE_NUGET_AUTH_TOKEN}} -s https://mindbox.myget.org/F/mindbox-private/api/v2
